"""Create ceel in map

Revision ID: 04b1e80850f0
Revises: 3f709dfd0e40
Create Date: 2024-06-26 11:02:08.563736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b1e80850f0'
down_revision = '3f709dfd0e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('top_left_lon', sa.Float(), nullable=False),
    sa.Column('top_left_lat', sa.Float(), nullable=False),
    sa.Column('bottom_right_lon', sa.Float(), nullable=False),
    sa.Column('bottom_right_lat', sa.Float(), nullable=False),
    sa.Column('valore', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell')
    # ### end Alembic commands ###
