"""New table environmental data

Revision ID: 181d1e7872ee
Revises: 1fed0269fa1c
Create Date: 2024-09-18 17:17:38.499551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181d1e7872ee'
down_revision = '1fed0269fa1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('battery_capacity', sa.Integer(), nullable=False),
    sa.Column('battery_lifetime', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('co2_scd41', sa.Integer(), nullable=False),
    sa.Column('co2_stc31c', sa.Integer(), nullable=False),
    sa.Column('voc', sa.Integer(), nullable=False),
    sa.Column('pm1_0', sa.Integer(), nullable=False),
    sa.Column('pm2_5', sa.Integer(), nullable=False),
    sa.Column('pm4_0', sa.Integer(), nullable=False),
    sa.Column('pm10', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environmental_data')
    # ### end Alembic commands ###
