"""New field user

Revision ID: 1fed0269fa1c
Revises: 9c4e27c7771e
Create Date: 2024-07-18 12:50:02.191230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fed0269fa1c'
down_revision = '9c4e27c7771e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('icon_type')

    # ### end Alembic commands ###
