"""empty message

Revision ID: 3f709dfd0e40
Revises: 
Create Date: 2024-06-24 12:24:26.474508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f709dfd0e40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('google_user', sa.Boolean(), nullable=True),
    sa.Column('punteggio', sa.Integer(), nullable=True),
    sa.Column('url_icon', sa.String(length=200), nullable=True),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('cognome', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
