"""New cell

Revision ID: 9c4e27c7771e
Revises: dd1f94c6c4ce
Create Date: 2024-07-01 17:39:12.593772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4e27c7771e'
down_revision = 'dd1f94c6c4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
