"""added last_aq_update field to Cell

Revision ID: cc39dbed56d7
Revises: 181d1e7872ee
Create Date: 2025-10-17 16:04:49.775067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc39dbed56d7'
down_revision = '181d1e7872ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_aq_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.drop_column('last_aq_update')

    # ### end Alembic commands ###
