"""New cell

Revision ID: dd1f94c6c4ce
Revises: 04b1e80850f0
Create Date: 2024-07-01 17:36:25.831188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1f94c6c4ce'
down_revision = '04b1e80850f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('air_quality', sa.Integer(), nullable=False))
        batch_op.drop_column('valore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valore', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('air_quality')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
