"""add cell_id to EnvironmentalData

Revision ID: e250bdbbc263
Revises: cc39dbed56d7
Create Date: 2025-11-12 17:12:27.428510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e250bdbbc263'
down_revision = 'cc39dbed56d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cell_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_environmental_data_cell_id'), ['cell_id'], unique=False)
        batch_op.create_foreign_key(None, 'cell', ['cell_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environmental_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_environmental_data_cell_id'))
        batch_op.drop_column('cell_id')

    # ### end Alembic commands ###
